// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as SocketIoClient from "socket.io-client";

function Client(Messages) {
  var emit = function (socket, obj) {
    socket.emit("message", obj);
    
  };
  var on = function (socket, func) {
    socket.on("message", Curry.__1(func));
    
  };
  var onConnect = function (socket, func) {
    socket.on("connect", (function (param) {
            return Curry._1(func, undefined);
          }));
    
  };
  var onDisconnect = function (socket, func) {
    socket.on("disconnect", (function (param) {
            return Curry._1(func, undefined);
          }));
    
  };
  return {
          io: (function (prim) {
              return SocketIoClient.io(prim);
            }),
          ioWithOptions: (function (prim0, prim1) {
              return SocketIoClient.io(prim0, prim1);
            }),
          emit: emit,
          on: on,
          onConnect: onConnect,
          onDisconnect: onDisconnect,
          disconnect: (function (prim) {
              prim.disconnect();
              
            })
        };
}

export {
  Client ,
  
}
/* socket.io-client Not a pure module */
