// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./ui/App.bs.js";
import * as React from "react";
import * as ReactDom from "react-dom";

var root = document.querySelector("#root");

if (root == null) {
  console.log("Error: could not find react element");
} else {
  ReactDom.render(React.createElement(React.StrictMode, {
            children: React.createElement(App.make, {})
          }), root);
}

if (import.meta.hot) {
  import.meta.hot.accept();
}

export {
  
}
/* root Not a pure module */
