// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as ChatMessages from "./ChatMessages.bs.js";
import * as SocketIOServer from "./bindings/SocketIOServer.bs.js";

var IO = SocketIOServer.Server(ChatMessages);

var state = {
  userCount: 0
};

var io = Curry._1(IO.createWithOptions, Curry._5(IO.makeOptions, undefined, undefined, undefined, {
          origin: "http://localhost:8080",
          methods: [
            "GET",
            "POST"
          ]
        }, undefined));

Curry._2(IO.onConnect, io, (function (socket) {
        state.userCount = state.userCount + 1 | 0;
        console.log("client connected");
        Curry._2(IO.emit, io, {
              TAG: /* UsersConnected */1,
              _0: state.userCount
            });
        Curry._2(IO.onDisconnect, socket, (function (param) {
                state.userCount = state.userCount - 1 | 0;
                Curry._2(IO.emit, io, {
                      TAG: /* UsersConnected */1,
                      _0: state.userCount
                    });
                console.log("client disconnected");
                
              }));
        return Curry._2(IO.on, socket, (function (msg) {
                      return Curry._2(IO.emitBroadcast, Curry._1(IO.broadcast, socket), {
                                  TAG: /* ChatMsg */0,
                                  _0: msg._0
                                });
                    }));
      }));

console.log("listening on port 4000");

Curry._2(IO.listen, io, 4000);

export {
  IO ,
  state ,
  io ,
  
}
/* IO Not a pure module */
